version: '3.7'

services:

  web:
    image: pekotify-premium-app:latest
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 5005:5005
    environment:
      - CHOKIDAR_USEPOLLING=true